# Inventory file for ssh_menu.py
# Example format:

#Role1:
#    Site1:
#        hostA:
#            username: exampleuser
#            xfoward: True
#            options: "-C"
#            port_forward:
#                local:
#                    local_port:
#                    remote_port:
#                    destination_server:
#                remote:
#                    local_port:
#                    remote_port:
#                dynamic:
#                    port:
#       hostB:
#   Site2:
#       hostC:
#Role2:
#   SiteB:
#       host2:
#---
#Defaults:
#   username: defaultuser
#   xfoward: False
#   options: "-C"
#   port_forward:
#       local:
#           local_port:
#           remote_port:
#           destination_server:
#       remote:
#           local_port:
#           remote_port:
#       dynamic:
#           port: